### PR TITLE
Add requirements.txt file to collate the dependencies

### LINKED ISSUE #1: Create a requirements.txt
The code needs a `requirements.txt` file that contains the list of all dependencies/modules. This would facilitate the convenient execution of the code.

### PR DESCRIPTION
**Pull request by surbhigoel77**
Closes #1

### CODE REVIEW

**Comment by ma595** [comment]
Please check if `xarray[netcdf4]` is needed, or if `pip install netcdf4` will suffice. 

We also need a version added to `scikit-learn`. 

A `frozen-requirements.txt` is provided in the notes repo.

**Review by ma595 — CHANGES_REQUESTED** [review]
I checked out the code again, pip installed the repo with `python==3.9` inside a `venv`, and the deployment works.  Check whether `xarray[complete]` is absolutely necessary.

**Comment by ma595** [comment]
@surbhigoel77, can you please confirm that the requirements install successfully and you have executed at least the `main_forcast.py` file.

**Review by isaacaka — APPROVED** [review]
These requirements work for me. `xarray[complete]` installs all necessary dependencies, `xarray[netcdf4]` does not. Good to merge.

**Review by ma595 — APPROVED** [review]

**Pull request merged**
